# vim: filetype=python
from os.path import join

Import('Env')

Env = Env.Clone()


Env.Append(CPPPATH=[
])


sources = Glob('*.cpp')
program = \
    Env.Program(
        target='wsgi-server',
        source=sources,
    )
