# vim: filetype=python
from os.path import exists, join

Import('Env')

# --------------------------------------------------------------------- #
targets = [
    'hello_world',
    'tutorial',
]
applications = []

# --------------------------------------------------------------------- #

for target in targets:
    scons = join(target, 'SConscript')
    if exists(scons):
        applications.append(
            Env.SConscript(scons, exports={'Env':Env}))
    else:
        sources = []
        paths = [
            './',
            './*',
            './*/*',
        ]
        for path in paths:
            sources.extend(Glob(join(target, '{}.cpp'.format(path))))

        applications.append(
            Env.Program(
                target=join(target, 'main'),
                source=sources,
                exports={'Env':Env}))

# --------------------------------------------------------------------- #
