#!/usr/bin/env python

from argparse import ArgumentParser
from jinja2   import Template

def main():
    argp = ArgumentParser()
    argp.add_argument('--input-csv'
                    , type     = str
                    , required = True)
    argp.add_argument('--input-template'
                    , type     = str
                    , required = True)
    argp.add_argument('--output-header'
                    , type     = str
                    , required = True)
    argp = argp.parse_args()

    # -- generate proper CSV list
    mimetypes = []
    with open(argp.input_csv) as fp:
        for name in fp:
            name = name.strip()
            template = name
            name = name.replace('/', '_')
            name = name.replace('+', '_')
            name = name.replace('.', '_')
            name = name.replace('-', '_')
            name = name.upper()

            if not name:
                continue
            mimetypes.append((name, template))
    
    mimetypes = sorted(set(mimetypes))
    # --
    with open(argp.input_template) as fp:
        template = Template(fp.read())
    
    # --
    with open(argp.output_header, 'wb') as fp:
        fp.write(template.render(mimetypes = mimetypes))

if __name__ == '__main__':
    main()
